### ISSUE TITLE
Delete python-configparser from the install script

### ISSUE THREAD

**Issue by ThePirateWhoSmellsOfSunflowers** [helios-4/sys-oled#5]
Hi!

You should remove the following dependency from the `install.sh` script : `python-configparser`. Indeed, on a fresh install (Armbian Buster in my case), this dependency installs python2 (+ dependencies), which is not ok I think. I've tested the install script without `python-configparser` and it works. As far as I understand, `configparser` is now part of the python3 standard library, so it should be installed by default on all modern systems.

:sunflower:

**Comment by g-provost** [comment]
Thanks for spotting that. You right the install shouldn't create a dependency on python2.
