### ISSUE TITLE
Error when setting up the OLED screen Helios4

### ISSUE THREAD

**Issue by jairunet** [helios-4/sys-oled#7]
Hello all I followed the instructions on the README.md document here in github, everything installed on the correct places but when starting the setup of the oled screen I am getting the following error:

$ sudo sys-oled --display ssd1306
Traceback (most recent call last):
  File "/usr/local/bin/sys-oled", line 142, in <module>
    main()
  File "/usr/local/bin/sys-oled", line 132, in main
    display_info(device)
  File "/usr/local/bin/sys-oled", line 105, in display_info
    draw.text((0, 0), cpu_usage(), font=font, fill="white")
  File "/usr/local/bin/sys-oled", line 78, in cpu_usage
    temp = psutil.sensors_temperatures()['f10e4078.thermal']
KeyError: 'f10e4078.thermal'

Any suggestions will be really appreciated.

Sincerely,

**Comment by pmontrasio** [comment]
The return value of `psutil.sensors_temperatures()` doesn't have `f10e4078.thermal` as a key on your machine. It depends on your device, maybe on the kernel or distro. Check what you have with

```
$ python3
import psutil
print(psutil.sensors_temperatures())
```

For example I have `cpu_thermal` and `soc_thermal` on two different machines.

Once you have found the right key, edit directly `/usr/local/bin/sys-oled`, then `sudo systemctl restart sys-oled.service` and you'll be ready to go.

**Comment by jairunet** [comment]
I ended up with this:

`#!/usr/bin/env python3

import signal
import os
import sys
import time
import psutil
import configparser
from datetime import datetime
from luma.core import cmdline, error
from luma.core.render import canvas
from PIL import Image, ImageDraw, ImageFont


# Load presets
contrast = 255
refresh = 10
show_logo = 'yes'
net_name =  'eth0'
s1_name = 'sd'
s1_path = '/'

# Load config file
config_file = '/etc/sys-oled.conf'
if os.path.isfile(config_file):
    config = configparser.ConfigParser()
    config.read(config_file)
    contrast = int(config.get('main', 'contrast'))
    refresh = float(config.get('main', 'refresh'))
    show_logo = config.get('main', 'show_logo')
    net_name = config.get('device', 'network_name')
    s1_name = config.get('device', 'storage1_name')
    s1_path = config.get('device', 'storage1_path')
    if config.has_option('device', 'storage2_name'):
        s2_name = config.get('device', 'storage2_name')
        s2_path = config.get('device', 'storage2_path')


# Load font
font_path = os.path.abspath(os.path.join(os.path.dirname(__file__),
                                '../share/sys-oled', 'C&C Red Alert [INET].ttf'))
font = ImageFont.truetype(font_path, 12)


def get_device(actual_args=None):
    if actual_args is None:
        actual_args = sys.argv[1:]
    parser = cmdline.create_parser(description='luma.core arguments')
    args = parser.parse_args(actual_args)

    if args.config:
        config = cmdline.load_config(args.config)
        args = parser.parse_args(config + actual_args)

    try:
        device = cmdline.create_device(args)
    except error.Error as e:
        parser.error(e)

    return device

def bytes2human(n):
    symbols = ('K', 'M', 'G', 'T', 'P', 'E', 'Z', 'Y')
    prefix = {}
    for i, s in enumerate(symbols):
        prefix[s] = 1 << (i + 1) * 10
    for s in reversed(symbols):
        if n >= prefix[s]:
            value = float(n) / prefix[s]
            if s in ['K', 'M']:
                return '%d%s' % (int(value), s)
            else:
                return '%.1f%s' % (value, s)
    return "%sB" % n

def mem_usage():
    usage = psutil.virtual_memory()
    return "mem: %s / %s - %.0f%%" \
        % (bytes2human(usage.used), bytes2human(usage.total), usage.percent)

def disk_usage(name, dir):
    usage = psutil.disk_usage(dir)
    return name + ": %s / %s - %.0f%%" \
        % (bytes2human(usage.used), bytes2human(usage.total), usage.percent)

def network(iface):
    addr = psutil.net_if_addrs()[iface]
    return "%s: %s" \
        % (iface, addr[0].address)

def host_time():
    now = datetime.now()
    hostname = os.uname()[1]
    return hostname + " " + now.strftime("%Y-%m-%d %H:%M")

def display_info(device):
    with canvas(device) as draw:
        draw.line((0,13)+(128,13), fill="white")
        draw.text((0, 15), mem_usage(), font=font, fill="white")
        draw.text((0, 27), disk_usage(s1_name, s1_path), font=font, fill="white")
        if 's2_name' in globals():
                draw.text((0, 39), disk_usage(s2_name, s2_path), font=font, fill="white")
                draw.text((0, 51), network(net_name), font=font, fill="white")
        else:
                draw.text((0, 39), network(net_name), font=font, fill="white")

def logo(device, msg):
    img_path = os.path.abspath(os.path.join(os.path.dirname(__file__),
        '../share/sys-oled', 'helios4_logo.png'))
    logo = Image.open(img_path).convert("RGBA")

    with canvas(device) as draw:
        draw.bitmap((0, 0), logo, fill="white")
        draw.text((0,52), msg, font=font, fill="white")

def sigterm_handler():
    sys.exit(0)

signal.signal(signal.SIGTERM, sigterm_handler)


def main():
    while True:
        display_info(device)
        time.sleep(refresh)
        if show_logo == "yes":
            logo(device, host_time())
            time.sleep(refresh / 2)

if __name__ == "__main__":
    try:
        device = get_device()
        device.contrast(contrast)
        main()
    except KeyboardInterrupt:
        pass`

**Comment by jairunet** [comment]
The LCD is now showing the correct values.  At least it's working.  Thank you for the suggestions.

Sincerely,
